# render.yaml
services:
  - type: web
    name: soilsense-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
